
spring:
  mail:
    host: smtp.gmail.com
    username: nguyenquyet101020@gmail.com
    password: fngtovihtmljmfbc
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true